countries = ['france', 'japan', 'usa', 'austria', 'russia']
print(f"\n{countries}")
print(f"\n{sorted(countries)}")
print(f"\n{countries}")
print(f"\n{sorted(countries, reverse=True)}")
print(f"\n{countries}")
countries.reverse()
print(f"\n{countries}")
countries.reverse()
countries.sort()
print(f"\n{countries}")
countries.sort(reverse=True)
print(f"\n{countries}")
